services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    networks:
      - trino-network
      - iceberg-network
    ports:
      - "8081:8081"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./properties/catalog:/etc/trino/catalog
      - ./properties/config.properties:/etc/trino/config.properties
      - ./properties/log.properties:/etc/trino/log.properties

networks:
  trino-network:
    name: trino_network
    driver: bridge
  iceberg-network:
    name: iceberg_network
    external: true